<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>JoystickMediaControl</AssemblyName>
    <Version>1.3.1</Version>
    <Company>Bartek16194</Company>
    <Authors>Bartek16194</Authors>
    <Description>Joystick and throttle media controls</Description>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RollForward>LatestMajor</RollForward>
    <PlatformTarget>x64</PlatformTarget>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
  </PropertyGroup>
</Project>
